### ISSUE TITLE
sickle pe makes unpaired output

### ISSUE THREAD

**Issue by dcopetti** [najoshi/sickle#49]
Hello,
After I run sickle pe
`sickle pe -f Sd5D_R1.fq -r Sd5D_R2.fq -t sanger -l 30 -o Sd5Db_R1.fq -p Sd5Db_R2.fq -s singles_Sd5Db`
and use the output in a different software, I get a warning that the reads in the files are not paired. Checking it, it is indeed unpaired:

```
> grep -n 'NB501259:17:HY3KTBGXX:3:11401:2371:1047' Sd5Db_20_R1.fq 
240364761:@NB501259:17:HY3KTBGXX:3:11401:2371:1047 1:N:0:CGATGG
> head -n 240364761 Sd5Db_20_R2.fq | tail -n 1
@NB501259:17:HY3KTBGXX:1:11101:2070:1080 2:N:0:CGATGT
```

I get the same issue on a different pair of inputs as well.
How do I preserve pairedness on a pe file?
Thanks, Dario

**Comment by najoshi** [comment]
Hi Dario,

Can you send me (or upload to a place where I can get to it) the files you
are working with so I can recreate the error?
- Nik.

On Thu, Jun 23, 2016 at 10:33 AM, dcopetti notifications@github.com wrote:

> Hello,
> After I run sickle pe
> sickle pe -f Sd5D_R1.fq -r Sd5D_R2.fq -t sanger -l 30 -o Sd5Db_R1.fq -p
> Sd5Db_R2.fq -s singles_Sd5Db
> and use the output in a different software, I get a warning that the reads
> in the files are not paired. Checking it, it is indeed unpaired:
> 
> > grep -n 'NB501259:17:HY3KTBGXX:3:11401:2371:1047' Sd5Db_20_R1.fq
> > 240364761:@NB501259:17:HY3KTBGXX:3:11401:2371:1047 1:N:0:CGATGG
> > head -n 240364761 Sd5Db_20_R2.fq | tail -n 1
> > @NB501259:17:HY3KTBGXX:1:11101:2070:1080 2:N:0:CGATGT
> 
> I get the same issue on a different pair of inputs as well.
> How do I preserve pairedness on a pe file?
> Thanks, Dario
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/najoshi/sickle/issues/49, or mute the thread
> https://github.com/notifications/unsubscribe/AAlGodEngZTixeOkCOcI2jq5cuEILOV_ks5qOsNZgaJpZM4I9DRV
> .

## 

Nikhil Joshi
Bioinformatics Analyst/Programmer
UC Davis Bioinformatics Core
http://bioinformatics.ucdavis.edu/
najoshi -at- ucdavis -dot- edu
530.752.2698 (w)

**Comment by dcopetti** [comment]
Sure,
here they are:
http://de.iplantcollaborative.org/dl/d/136814CD-3D4B-41A0-9F48-BDB59A5826A7/Sd5D_R1.fq
http://de.iplantcollaborative.org/dl/d/E4770F93-B4C6-43E2-A976-BC2D905D8315/Sd5D_R2.fq
please keep confidential.
Thansk,

Dario

On 06/23/2016 01:09 PM, najoshi wrote:
> Hi Dario,
>
> Can you send me (or upload to a place where I can get to it) the files you
> are working with so I can recreate the error?
>
> - Nik.
>
> On Thu, Jun 23, 2016 at 10:33 AM, dcopetti <notifications@github.com> 
> wrote:
>
> > Hello,
> > After I run sickle pe
> > sickle pe -f Sd5D_R1.fq -r Sd5D_R2.fq -t sanger -l 30 -o Sd5Db_R1.fq -p
> > Sd5Db_R2.fq -s singles_Sd5Db
> > and use the output in a different software, I get a warning that the 
> reads
> > in the files are not paired. Checking it, it is indeed unpaired:
> >
> > > grep -n 'NB501259:17:HY3KTBGXX:3:11401:2371:1047' Sd5Db_20_R1.fq
> > 240364761:@NB501259:17:HY3KTBGXX:3:11401:2371:1047 1:N:0:CGATGG
> > > head -n 240364761 Sd5Db_20_R2.fq | tail -n 1
> > @NB501259:17:HY3KTBGXX:1:11101:2070:1080 2:N:0:CGATGT
> >
> > I get the same issue on a different pair of inputs as well.
> > How do I preserve pairedness on a pe file?
> > Thanks, Dario
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/najoshi/sickle/issues/49>, or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/AAlGodEngZTixeOkCOcI2jq5cuEILOV_ks5qOsNZgaJpZM4I9DRV>
> > .
> >
>
>
>
> -- 
> Nikhil Joshi
> Bioinformatics Analyst/Programmer
> UC Davis Bioinformatics Core
> http://bioinformatics.ucdavis.edu/
> najoshi -at- ucdavis -dot- edu
> 530.752.2698 (w)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/najoshi/sickle/issues/49#issuecomment-228168536>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ANM2XikycWkMXFgy57rxESSwzdfX7dN1ks5qOufkgaJpZM4I9DRV>.
>

-- 
Dario Copetti, PhD
Research Associate | Arizona Genomics Institute
University of Arizona | BIO5

1657 E. Helen St.
Tucson, AZ  85721, USA
www.genome.arizona.edu

**Comment by tsibley** [comment]
@dcopetti You've just posted those links to a public issue tracker.  If you want to keep the data confidential, you should remove the uploaded files ASAP.

**Comment by dcopetti** [comment]
Thanks @tsibley! How do I get confidentially in contact with Nik then? my email is dcopetti{}emai[]arizona[]edu

**Comment by tsibley** [comment]
The most recent commit to sickle by @najoshi is with the email address najoshi at ucdavis.edu.

**Comment by llq0325** [comment]
Hi,

I wonder if you figure out what is going wrong here? I also got error when using sickle trimmed PE reads in BWA-MEM.
